#if defined(DEFINE_IN_INTERFACE)
#undef MSG_H_
#endif

#ifndef MSG_H_
#define MSG_H_

#include "net\Message_Defs.h"
#include "net\Message.h"
#include "net\Bundle.h"

MSGS_DECL_NAMESPACE_BEGIN(SRV)
NET_MSG_ARGS3_DECL(srv, msg1, Message, NETWORK_FIXED_MESSAGE, ACE_UINT64, INT1, ACE_UINT64, INT2, ACE_UINT64, INT3)
NET_MSG_STREAM_DELC(srv, msg2, Message, NETWORK_VARIABLE_MESSAGE)
NET_MSG_ARGS3_DECL(srv, msg3, Message, NETWORK_FIXED_MESSAGE, ACE_UINT64, INT1, ACE_UINT64, INT2, ACE_UINT64, INT3)
NET_MSG_STREAM_DELC(srv, msg4, Message, NETWORK_VARIABLE_MESSAGE)
MSGS_DECL_NAMESPACE_END()

//#define DEFINE_IN_INTERFACE
//#include "net\Message_Defs.h"
//#include "net\Message.h"
//#include "net\Bundle.h"
//
//MSGS_DECL_NAMESPACE_BEGIN(Test)
//NET_MSG_ARGS3_DECL(srv, msg1, Message, NETWORK_FIXED_MESSAGE, UINT64, INT1, UINT64, INT2, UINT64, INT3)
//NET_MSG_STREAM_DELC(srv, msg2, Message, NETWORK_VARIABLE_MESSAGE)
//NET_MSG_ARGS3_DECL(srv, msg3, Message, NETWORK_FIXED_MESSAGE, UINT64, INT1, UINT64, INT2, UINT64, INT3)
//NET_MSG_STREAM_DELC(srv, msg4, Message, NETWORK_VARIABLE_MESSAGE)
//MSGS_DECL_NAMESPACE_END()
#endif